/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAkademiRouteImport } from './routes/_authenticated/akademi'
import { Route as AuthenticatedAlatRouteImport } from './routes/_authenticated/alat'
import { Route as AuthenticatedCmsRouteImport } from './routes/_authenticated/cms'
import { Route as AuthenticatedDompetRouteImport } from './routes/_authenticated/dompet'
import { Route as AuthenticatedJamaahRouteImport } from './routes/_authenticated/jamaah'
import { Route as AuthenticatedJaringanRouteImport } from './routes/_authenticated/jaringan'
import { Route as AuthenticatedLeaderboardRouteImport } from './routes/_authenticated/leaderboard'
import { Route as AuthenticatedMuslimRouteImport } from './routes/_authenticated/muslim'
import { Route as AuthenticatedSegmentasiRouteImport } from './routes/_authenticated/segmentasi'
import { Route as AuthenticatedTeritorialRouteImport } from './routes/_authenticated/teritorial'

const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/_authenticated/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAkademiRoute = AuthenticatedAkademiRouteImport.update({
  id: '/_authenticated/akademi',
  path: '/akademi',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAlatRoute = AuthenticatedAlatRouteImport.update({
  id: '/_authenticated/alat',
  path: '/alat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCmsRoute = AuthenticatedCmsRouteImport.update({
  id: '/_authenticated/cms',
  path: '/cms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDompetRoute = AuthenticatedDompetRouteImport.update({
  id: '/_authenticated/dompet',
  path: '/dompet',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedJamaahRoute = AuthenticatedJamaahRouteImport.update({
  id: '/_authenticated/jamaah',
  path: '/jamaah',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedJaringanRoute = AuthenticatedJaringanRouteImport.update({
  id: '/_authenticated/jaringan',
  path: '/jaringan',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLeaderboardRoute =
  AuthenticatedLeaderboardRouteImport.update({
    id: '/_authenticated/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedMuslimRoute = AuthenticatedMuslimRouteImport.update({
  id: '/_authenticated/muslim',
  path: '/muslim',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSegmentasiRoute = AuthenticatedSegmentasiRouteImport.update({
  id: '/_authenticated/segmentasi',
  path: '/segmentasi',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTeritorialRoute = AuthenticatedTeritorialRouteImport.update({
  id: '/_authenticated/teritorial',
  path: '/teritorial',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/akademi': typeof AuthenticatedAkademiRoute
  '/alat': typeof AuthenticatedAlatRoute
  '/cms': typeof AuthenticatedCmsRoute
  '/dompet': typeof AuthenticatedDompetRoute
  '/jamaah': typeof AuthenticatedJamaahRoute
  '/jaringan': typeof AuthenticatedJaringanRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/muslim': typeof AuthenticatedMuslimRoute
  '/segmentasi': typeof AuthenticatedSegmentasiRoute
  '/teritorial': typeof AuthenticatedTeritorialRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesByTo {
  '/akademi': typeof AuthenticatedAkademiRoute
  '/alat': typeof AuthenticatedAlatRoute
  '/cms': typeof AuthenticatedCmsRoute
  '/dompet': typeof AuthenticatedDompetRoute
  '/jamaah': typeof AuthenticatedJamaahRoute
  '/jaringan': typeof AuthenticatedJaringanRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/muslim': typeof AuthenticatedMuslimRoute
  '/segmentasi': typeof AuthenticatedSegmentasiRoute
  '/teritorial': typeof AuthenticatedTeritorialRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated/akademi': typeof AuthenticatedAkademiRoute
  '/_authenticated/alat': typeof AuthenticatedAlatRoute
  '/_authenticated/cms': typeof AuthenticatedCmsRoute
  '/_authenticated/dompet': typeof AuthenticatedDompetRoute
  '/_authenticated/jamaah': typeof AuthenticatedJamaahRoute
  '/_authenticated/jaringan': typeof AuthenticatedJaringanRoute
  '/_authenticated/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/_authenticated/muslim': typeof AuthenticatedMuslimRoute
  '/_authenticated/segmentasi': typeof AuthenticatedSegmentasiRoute
  '/_authenticated/teritorial': typeof AuthenticatedTeritorialRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/akademi'
    | '/alat'
    | '/cms'
    | '/dompet'
    | '/jamaah'
    | '/jaringan'
    | '/leaderboard'
    | '/muslim'
    | '/segmentasi'
    | '/teritorial'
    | '/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/akademi'
    | '/alat'
    | '/cms'
    | '/dompet'
    | '/jamaah'
    | '/jaringan'
    | '/leaderboard'
    | '/muslim'
    | '/segmentasi'
    | '/teritorial'
    | '/'
  id:
    | '__root__'
    | '/_authenticated/akademi'
    | '/_authenticated/alat'
    | '/_authenticated/cms'
    | '/_authenticated/dompet'
    | '/_authenticated/jamaah'
    | '/_authenticated/jaringan'
    | '/_authenticated/leaderboard'
    | '/_authenticated/muslim'
    | '/_authenticated/segmentasi'
    | '/_authenticated/teritorial'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedAkademiRoute: typeof AuthenticatedAkademiRoute
  AuthenticatedAlatRoute: typeof AuthenticatedAlatRoute
  AuthenticatedCmsRoute: typeof AuthenticatedCmsRoute
  AuthenticatedDompetRoute: typeof AuthenticatedDompetRoute
  AuthenticatedJamaahRoute: typeof AuthenticatedJamaahRoute
  AuthenticatedJaringanRoute: typeof AuthenticatedJaringanRoute
  AuthenticatedLeaderboardRoute: typeof AuthenticatedLeaderboardRoute
  AuthenticatedMuslimRoute: typeof AuthenticatedMuslimRoute
  AuthenticatedSegmentasiRoute: typeof AuthenticatedSegmentasiRoute
  AuthenticatedTeritorialRoute: typeof AuthenticatedTeritorialRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/akademi': {
      id: '/_authenticated/akademi'
      path: '/akademi'
      fullPath: '/akademi'
      preLoaderRoute: typeof AuthenticatedAkademiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/alat': {
      id: '/_authenticated/alat'
      path: '/alat'
      fullPath: '/alat'
      preLoaderRoute: typeof AuthenticatedAlatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/cms': {
      id: '/_authenticated/cms'
      path: '/cms'
      fullPath: '/cms'
      preLoaderRoute: typeof AuthenticatedCmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dompet': {
      id: '/_authenticated/dompet'
      path: '/dompet'
      fullPath: '/dompet'
      preLoaderRoute: typeof AuthenticatedDompetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/jamaah': {
      id: '/_authenticated/jamaah'
      path: '/jamaah'
      fullPath: '/jamaah'
      preLoaderRoute: typeof AuthenticatedJamaahRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/jaringan': {
      id: '/_authenticated/jaringan'
      path: '/jaringan'
      fullPath: '/jaringan'
      preLoaderRoute: typeof AuthenticatedJaringanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/leaderboard': {
      id: '/_authenticated/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AuthenticatedLeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/muslim': {
      id: '/_authenticated/muslim'
      path: '/muslim'
      fullPath: '/muslim'
      preLoaderRoute: typeof AuthenticatedMuslimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/segmentasi': {
      id: '/_authenticated/segmentasi'
      path: '/segmentasi'
      fullPath: '/segmentasi'
      preLoaderRoute: typeof AuthenticatedSegmentasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/teritorial': {
      id: '/_authenticated/teritorial'
      path: '/teritorial'
      fullPath: '/teritorial'
      preLoaderRoute: typeof AuthenticatedTeritorialRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedAkademiRoute: AuthenticatedAkademiRoute,
  AuthenticatedAlatRoute: AuthenticatedAlatRoute,
  AuthenticatedCmsRoute: AuthenticatedCmsRoute,
  AuthenticatedDompetRoute: AuthenticatedDompetRoute,
  AuthenticatedJamaahRoute: AuthenticatedJamaahRoute,
  AuthenticatedJaringanRoute: AuthenticatedJaringanRoute,
  AuthenticatedLeaderboardRoute: AuthenticatedLeaderboardRoute,
  AuthenticatedMuslimRoute: AuthenticatedMuslimRoute,
  AuthenticatedSegmentasiRoute: AuthenticatedSegmentasiRoute,
  AuthenticatedTeritorialRoute: AuthenticatedTeritorialRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
